services:
  c:
    image: emscripten/emsdk:3.1.24
    container_name: greenlab-c
    volumes:
      - ../../applications:/var/compilation
    working_dir: /var/compilation/${GREENLAB_BENCHMARK_NAME}/c
    command: emcc main.c -o ${GREENLAB_BENCHMARK_NAME}.c.wasm

  rust:
    build:
      context: ./rust
    container_name: greenlab-rust
    volumes:
      - ../../applications:/var/compilation
    working_dir: /var/compilation/${GREENLAB_BENCHMARK_NAME}/rust
    command: cargo build --target wasm32-wasi --release

  javascript:
    build:
      context: ./javascript
    container_name: greenlab-javascript
    volumes:
      - ../../applications:/var/compilation
    working_dir: /var/compilation/${GREENLAB_BENCHMARK_NAME}/javascript
    command: /var/javy/target/release/javy index.js -o ${GREENLAB_BENCHMARK_NAME}.javascript.wasm

  go:
    image: tinygo/tinygo:0.26.0
    container_name: greenlab-go
    volumes: 
      - ../../applications:/var/compilation
    working_dir: /var/compilation/${GREENLAB_BENCHMARK_NAME}/go
    command: tinygo build -o ${GREENLAB_BENCHMARK_NAME}.go.wasm -target wasm --no-debug ./main.go


