---
- hosts: managers
  tasks:
    - name: Install Docker Dependencies
      remote_user: green-lab-tester
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - gnupg
        - ca-certificates
        - curl
        - lsb-release
      tags:
        - docker

    - name: Add Docker's GPG key
      remote_user: green-lab-tester
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Set up the stable repository
      remote_user: green-lab-tester
      shell: >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      tags:
        - docker

    - name: Update apt cache
      remote_user: green-lab-tester
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install Docker & Compose Plugin
      remote_user: green-lab-tester
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-compose-plugin
      tags:
        - docker

    - name: Add "green-lab-tester" to "docker" group
      remote_user: green-lab-tester
      user:
        name: "green-lab-tester"
        group: "docker"
        append: yes
      tags:
        - docker
